version: '3'
services:
  stellar:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "11625:11625"
      - "11626:11626"
    volumes:
      - "./stellar:/opt/stellar"
      - "./var/log/supervisor/:/var/log/supervisor/"
    environment:
      - PGPASS=test
      - NETWORK=pubnet