version: 2.1

commands:
  checkout:
    steps:
      - run:
          name: checkout
          command: |
            # Copy of the upstream checkout command with the following modifications:
            # 1. CIRCLE_REPOSITORY_URL is updated to use https rather than ssh
            # 2. Removed ssh specific sections

            # Use https rather than ssh to clone public projects
            CIRCLE_REPOSITORY_URL=${CIRCLE_REPOSITORY_URL/://}
            CIRCLE_REPOSITORY_URL=${CIRCLE_REPOSITORY_URL/git@/https://}

            echo "Repository URL: ${CIRCLE_REPOSITORY_URL}"

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            # Ensure ~ is expanded otherwise bash treats is as string literal
            eval CIRCLE_WORKING_DIRECTORY=${CIRCLE_WORKING_DIRECTORY}
            if [ -e ${CIRCLE_WORKING_DIRECTORY}/.git ]
            then
              cd ${CIRCLE_WORKING_DIRECTORY}
              git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
            else
              mkdir -p ${CIRCLE_WORKING_DIRECTORY}
              cd ${CIRCLE_WORKING_DIRECTORY}
              git clone "$CIRCLE_REPOSITORY_URL" .
            fi

            if [ -n "$CIRCLE_TAG" ]
            then
              git fetch --force origin "refs/tags/${CIRCLE_TAG}"
            else
              # By default "git fetch" only fetches refs/<branchname>
              # Below ensures we also fetch PR refs
              git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pull/*"
              git fetch --force --quiet origin
            fi

            if [ -n "$CIRCLE_TAG" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q "$CIRCLE_TAG"
            elif [ -n "$CIRCLE_BRANCH" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q -B "$CIRCLE_BRANCH"
            fi

            git reset --hard "$CIRCLE_SHA1"

jobs:
  publish_docker_image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker build -t stellar/quickstart:latest .
            docker push stellar/quickstart:latest
            docker build -f Dockerfile.testing -t stellar/quickstart:testing .
            docker push stellar/quickstart:testing

workflows:
  version: 2

  publish:
    jobs:
      - publish_docker_image:
          filters:
              branches:
                only:
                  - master