name: Test

on:
  push:
    branches: master
  pull_request:

jobs:

  test:
    strategy:
      matrix:
        network: [testnet, pubnet]
        dockerfile: [Dockerfile, Dockerfile.testing]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Quickstart Image
      run: docker build -f ${{ matrix.dockerfile }} -t stellar-quickstart .

    - name: Run Quickstart Image
      run: docker run --rm -d -p "8000:8000" --name stellar stellar-quickstart --${{ matrix.network }}

    - name: Sleep until supervisor is up
      run: sleep 10
    
    - name: Tail supervisor
      run: |
        echo "supervisorctl tail -f stellar-core" | docker exec -i stellar sh &
        echo "supervisorctl tail -f horizon" | docker exec -i stellar sh &

    - name: Wait for Horizon to have started ingesting
      run: while ! [ "$(curl -s --fail localhost:8000 | tee >(cat 1>&2) | jq '.history_latest_ledger')" -gt 0 ]; do echo; date; echo 'Waiting...'; sleep 10; done
